version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'

  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'


  emailling-service-db:
    image: ${EMAILLING_SERVICE_DB_IMAGE_NAME}
    container_name: ${EMAILLING_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${EMAILLING_SERVICE_DB_PORT}:${EMAILLING_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${EMAILLING_SERVICE_DB_NAME}
      - MYSQL_USER=${EMAILLING_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${EMAILLING_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${EMAILLING_SERVICE_DB_PASSWORD_ROOT}

  emailling-service-back:
    build: ${EMAILLING_SERVICE_PROJECT_PATH}
    container_name: ${EMAILLING_SERVICE_CONTAINER_NAME}
    image: ${EMAILLING_SERVICE_IMAGE_NAME}
    ports:
      - "${EMAILLING_SERVICE_BACK_PORT}:${EMAILLING_SERVICE_BACK_PORT}"
    environment:
      - EMAILLING_SERVICE_DB_URL=jdbc:mysql://emailling-service-db:3306/${EMAILLING_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - EMAILLING_SERVICE_DB_USER=${EMAILLING_SERVICE_DB_USER}
      - EMAILLING_SERVICE_DB_PASSWORD=${EMAILLING_SERVICE_DB_PASSWORD}
    depends_on:
      - emailling-service-db



volumes:
  app-data:

